# Publish all joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Control all joints
arm_controller:
  type: "arm_control/JointTrajectoryController"
  joints:
    - base_link__link_01
    - link_01__link_02
    - link_02__link_03
    - link_03__link_04
    - link_04__electric_gripper

  gains:
    base_link__link_01: {p: 300,  d: 50}
    link_01__link_02: {p: 300,  d: 50}
    link_02__link_03: {p: 300,  d: 50}
    link_03__link_04: {p: 200,  d: 20}
    link_04__electric_gripper: {p: 200,  d: 20}

  constraints:
    base_link__link_01: 
      trayectory: 1.0
      goal: 1.0
    link_01__link_02: 
      trayectory: 1.0
      goal: 1.0
    link_02__link_03: 
      trayectory: 1.0
      goal: 1.0
    link_03__link_04: 
      trayectory: 1.0
      goal: 1.0
    link_04__electric_gripper: 
      trayectory: 1.0
      goal: 1.0
