controller_list:
  - name: fake_arm_controller
    joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
  - name: fake_gripper_controller
    joints:
      - link_04__electric_gripper
      - electric_gripper__clamp_l
      - electric_gripper__clamp_r