# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_01
  pid: {p: 2000.0, i: 100, d: 500.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_01__link_02
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_02__link_03
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_03__link_04
  pid: {p: 20000.0, i: 100, d: 100.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_04__electric_gripper
  pid: {p: 10000.0, i: 50, d: 500.0}
clamp_r_position_controller:
  type: effort_controllers/JointPositionController
  joint: electric_gripper__clamp_r
  pid: {p: 100.0, i: 5, d: 50.0}
clamp_l_position_controller:
  type: effort_controllers/JointPositionController
  joint: electric_gripper__clamp_l
  pid: {p: 100.0, i: 5, d: 50.0}
